name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: MalekJamal
          outputs: |
            ./github-snake.svg
            ./github-snake-dark.svg?palette=github-dark

      - name: Push Snake Animation to GitHub
        run: |
          git config --global user.name 'Malek Jamal'
          git config --global user.email 'malekhamdan82@gmail.com'
          git add .
          git commit -m "Generate contribution snake animation"
          git push
